// Every visible admin sentence of the finder redesign (docs/finder-ux-spec.md §7).
// Plain data — no React, no "use client" — so node --test can walk every string
// and assert the forbidden-token list (wording.test.ts). Prospect-facing FR/EN
// strings live elsewhere and are untouched. Placeholders are {name} tokens
// filled by fill(); numbers are formatted by the caller (format.ts).
import type { RefusalCode } from "../../lib/crm/types.ts";

/** Replace {token} placeholders; unknown tokens stay visible so a miss is obvious in a test. */
export function fill(template: string, params: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in params ? String(params[k]) : m));
}

export const ATTRIBUTION_TEXT =
  "Données © les contributeurs d'OpenStreetMap (ODbL) · Sirene/RNE via API Recherche d'entreprises — Licence Ouverte 2.0 · Companies House — OGL v3";

/** Sources as words (never abbreviations). */
export const SOURCE_WORDS = {
  osm: "OpenStreetMap",
  fr_register: "French company register",
  companies_house: "Companies House",
  google: "Google",
  manual: "Added by its website",
} as const;

export const FIND_TEXT = {
  title: "Find businesses",
  intro: "Any place on the map and a trade. Saving a business starts its 30-day notice clock.",
  areaLabel: "Area",
  areaPlaceholder: "Town, postcode, department, region or country — e.g. Foix, 09000, Ariège, Occitanie, Andorra",
  areaHint: "Any place OpenStreetMap knows. Large areas take longer and stop at 2,000 businesses.",
  tradeLabel: "Trade",
  tradePlaceholder: "Type a trade — Restaurant, Bakery, Plumber…",
  otherTrade: "Other trade…",
  customCategory: "Map category",
  customValue: "Map value",
  customValueHint: "lower-case letters and underscores, e.g. tattoo",
  customName: "Name to store",
  customNaf: "French activity code (optional, e.g. 96.09Z) — needed for the register",
  customSic: "UK code (optional, 5 digits) — needed for Companies House",
  sourcesButton: "Sources: {list}",
  sourcesTitle: "Where to look",
  sourceOsm: "OpenStreetMap (the open map: signs, phones, websites)",
  sourceRegister: "French company register (Sirene — legal identity, France only)",
  sourceCompaniesHouse: "Companies House (UK register)",
  sourceGoogle: "Google",
  sourceNeedsKey: "needs an API key",
  sourceSwitchedOff: "switched off",
  helper: "Public sources only, one request per second, results kept for 24 hours.",
  search: "Search",
  stop: "Stop",
  typeAreaFirst: "Type an area first.",
  candidatesTitle: "Which one?",
  candidate: "{label} — {kind}, {country}",
  resolving: "Finding “{query}”…",
  resolved: "{area} — {kind}, {country}",
  estimate: "about {n} {trade} on the map",
  estimateUnknown: "the count grows as areas finish",
  notThisPlace: "Not this place?",
  gateTitle: "About {expected} {trade} in {area}. One search holds {cap}.",
  gateTitleUnknown: "{area} is a large area. One search holds {cap} businesses.",
  gateChildren: "Search one {child} instead — everything there is included:",
  gateNoChildren: "{area} is too large for one search — type one of its {children} in the Area box.",
  gateContinue: "Continue with the {cap} nearest the centre",
  gateChange: "Change area",
  searchingOsm: "Searching OpenStreetMap — {done} of {total} areas",
  searchingOsmOne: "Searching OpenStreetMap",
  foundSoFar: "{n} businesses so far",
  eta: "about {s} left",
  searchingFor: "searching for {s}",
  longerThanUsual: "taking longer than usual",
  checkingRegister: "Checking the French company register — {done} of {total} pages",
  checkingRegisterScopes: "Checking the French company register — {done} of {total} areas",
  placing: "Placing on the map and removing duplicates…",
  retrying: "The map service is busy — retrying in {s} s",
  done: "{n} businesses in {area} · {onMap} on the map, {inRegister} in the register, {inBoth} in both{extra} · {duration}.",
  doneNoRegister: "{n} businesses in {area} · {onMap} on the map{extra} · {duration}.",
  duplicatesRemoved: "{n} duplicates removed",
  fromEarlier: "map read {when} (kept 24 hours)",
  notesDetails: "Details ({n})",
  cancelled: "Stopped after {done} of {total} areas — {n} businesses kept",
  continueBtn: "Continue",
  retryMissing: "Retry the missing areas",
  runAgain: "Run again",
  openIt: "Open it",
  stopIt: "Stop it",
  searchDepartment: "Search a smaller area:",
  empty: "No {trade} found in {area} on OpenStreetMap. The map may simply not list them yet — try a wider area or another trade.",
  summary: "{n} businesses in {area}",
  summaryOne: "1 business in {area}",
  summarySavable: "{n} can be saved",
  perSource: "from OpenStreetMap {onMap} · from the register {inRegister}",
  perSourceRunning: "from OpenStreetMap {onMap} · from the register {inRegister} yet",
  saveTicked: "Save ticked ({n})",
  filtersLabel: "Filters",
  chipSavable: "Can be saved",
  chipNotListed: "Not listed publicly",
  chipWebsite: "Has website",
  chipNoWebsite: "No website",
  chipPhone: "Has phone",
  chipEmail: "Has email",
  chipRegister: "In the register",
  chipSaved: "Saved",
  chipHidden: "Hidden",
  filterPlaceholder: "Filter by name or town",
  sortLabel: "Sort",
  sortNearest: "Nearest the centre",
  sortComplete: "Most complete first",
  sortHint: "Businesses that cannot be saved (not listed publicly, closed, hidden) always come last.",
  sortTown: "Town A–Z",
  sortName: "Name A–Z",
  followMap: "List follows the map",
  showMore: "Show {n} more",
  townUnknown: "town unknown",
  nearTown: "near {town}",
  notOnMap: "Not on the map — the register gives no coordinates for this establishment",
  undo: "Undo",
  hiddenRow: "Hidden",
  pastSearches: "Past searches",
  noPastSearches: "No searches yet.",
  pastRow: "{area} · {trade} — {found} found · {saved} saved · {when}",
  listControl: "List",
  mapControl: "Map",
  back: "Back",
  close: "Close",
  showOnMap: "Show on map",
  legend: "Legend",
  approxOutline: "approximate outline",
  unitFailed: "{unit} — could not be searched",
  unitDone: "{unit} — done",
  unitRunning: "{unit} — searching",
  outsideArea: "Outside {area}?",
  savedAs: "Saved as {reference} · audit queued",
  savedAsNoWebsite: "Saved as {reference} · no website to audit",
  savedBulk: "Saved {saved} · {audits} audits queued · {without} without a website",
  saveFailed: "Could not save — try again.",
  saveHidden: "This business is hidden — undo first.",
  saveNotListed: "Not listed publicly — the register hides its details, so it cannot be saved.",
  saveExpired: "This search is more than a day old — run it again.",
  dismissed: "Hidden — {name}",
} as const;

export const CARD_TEXT = {
  chain: "Part of the {brand} chain",
  where: "Where",
  about: "About the business",
  cuisine: "Cuisine: {v}",
  openingHours: "Open: {v}",
  searchGoogle: "Search Google for “{q}”",
  contact: "Contact",
  register: "Register",
  origin: "Where it came from",
  nearTownNoStreet: "near {town} — the source has no street address",
  countryAssumed: "(assumed from the search area)",
  distance: "{km} km from the centre of {area}",
  openOsm: "Open in OpenStreetMap",
  openGoogleMaps: "Open in Google Maps",
  website: "Website",
  phone: "Phone",
  email: "Email",
  facebook: "Facebook",
  instagram: "Instagram",
  linkedin: "LinkedIn",
  twitter: "X",
  listedRegister: "Listed in the French company register — {legalName}, SIRET {siret}, {form}, {state}.",
  listedRegisterShort: "Listed in the French company register — SIRET {siret}, {form}, {state}.",
  active: "active",
  closed: "closed",
  publiclyListed: "Publicly listed.",
  notListedPublicly: "Not listed publicly — the owner asked the register to hide the details, so this business cannot be saved or contacted.",
  openRegister: "Open in the register (annuaire-entreprises)",
  notMatched: "Not matched to a register entry yet — the register is checked again after saving.",
  companiesHouse: "Companies House — company {number}, {status}; registered office, not necessarily the shop.",
  fromOsm: "Found on OpenStreetMap (the open map anyone can edit) — {type} {id}, read {date}",
  fromRegister: "Listed in the French company register (Sirene, public data)",
  fromCompaniesHouse: "Listed at Companies House (public data)",
  fromGoogle: "Found on Google",
  fromBoth: "Found on OpenStreetMap and matched to the French register.",
  saveAudit: "Save & audit",
  save: "Save",
  noWebsiteToAudit: "No website to audit — the audit needs one",
  notThisOne: "Not this one",
  openProspect: "Open prospect",
  alreadySaved: "Already saved — Open prospect {reference}",
  closedInRegister: "Closed in the register — cannot be saved",
  hidden: "Hidden with “Not this one” — undo to save",
  saving: "Saving…",
} as const;

export const ERROR_TEXT = {
  area_not_found: "Nothing found for “{query}”. Try a town, a postcode, a department, a region or a country.",
  geocode_failed: "The place lookup did not answer. Try again in a minute.",
  search_running: "A search is already running ({area} · {trade}).",
  bad_category: "Pick a trade, or fill in the custom trade (map value: lower-case letters and underscores).",
  bad_area: "That area could not be used. Try another name.",
  search_expired: "This search is more than a day old and its results were cleared. Run it again.",
  not_continuable: "This search cannot be continued — run it again.",
  search_failed: "The search failed. Try again.",
} as const;

/** Finder status words (list column and card). */
export const STATUS_WORDS = {
  saved: "Saved",
  not_listed: "Not listed publicly",
  closed: "Closed in the register",
  chain: "Chain",
  outside: "Outside the area?",
  hidden: "Hidden",
} as const;

/** Search status → one word for past searches and banners. */
export const SEARCH_STATUS_WORDS = {
  running: "running",
  done: "complete",
  capped: "stopped at the cap",
  partial: "some areas missing",
  failed: "failed",
  cancelled: "stopped",
  interrupted: "interrupted",
  expired: "results cleared",
} as const;

export const AREA_KIND_WORDS = {
  town: "town",
  postcode: "postcode",
  department: "department",
  region: "region",
  country: "country",
  place: "place",
} as const;

/** The over-cap gate names the children by the parent's kind. */
export const CHILD_KIND_WORDS = {
  country: "region",
  region: "department",
  department: "town",
  town: "part",
  postcode: "part",
  place: "part",
} as const;

/** "…type one of its {children} in the Area box." */
export const CHILD_KIND_WORDS_PLURAL = {
  country: "regions or departments",
  region: "departments",
  department: "towns",
  town: "districts, or a postcode",
  postcode: "streets or districts",
  place: "smaller areas",
} as const;

export const LEGEND_TEXT = {
  title: "What the map shows",
  pinWebsite: "Filled pink pin — has a website",
  pinNoWebsite: "Hollow pin — no website yet",
  pinSaved: "Green pin — already saved as a prospect",
  pinHidden: "Grey pin — hidden with “Not this one” (shown with the Hidden filter)",
  pinOutside: "Amber ring — probably outside the area (the register gave no exact position)",
  pinSelected: "White ring — the business you are looking at",
  outline: "Dashed orange line — the area searched; nothing outside it is requested",
  units: "Small dots — parts of a large area: green done, red could not be searched, pulsing in progress",
  cluster: "Numbered discs — several businesses close together; click to zoom in",
  statusTitle: "Words in the list",
  statusSaved: "Saved — already a prospect; the reference opens it",
  statusNotListed: "Not listed publicly — the register hides the details; cannot be saved",
  statusClosed: "Closed in the register — the establishment has ceased",
  statusChain: "Chain — part of a brand",
  statusOutside: "Outside the area? — the register gave no exact position",
} as const;

/** Prospect badge keys (ProspectBadges.tsx) → the word shown and the sentence behind it. */
export const BADGE_TEXT: Record<string, { label: string; sentence: string }> = {
  removed: { label: "Not this business", sentence: "Marked as not this business — hidden from every view." },
  optout: { label: "Opted out", sentence: "Asked not to be contacted — on the opposition list." },
  ceased: { label: "Closed in the register", sentence: "The register says the establishment has ceased." },
  partial: { label: "Not listed publicly", sentence: "The owner asked the register to hide the details: cannot be saved or contacted." },
  forbids: { label: "Site forbids prospecting", sentence: "The website's legal page forbids extraction or prospecting." },
  "forbids-override": { label: "Prospecting allowed (reason on file)", sentence: "The site forbids prospecting, but a reason to go ahead is recorded." },
  "not-fit": { label: "Not a fit", sentence: "You decided this business is not a fit." },
  fit: { label: "Good fit", sentence: "You marked this business as a good fit." },
  "no-website": { label: "No website", sentence: "No website on file — nothing to audit yet." },
  call: { label: "Call (no email)", sentence: "No usable business email, but a phone number is on file." },
  "no-email": { label: "No email found", sentence: "No business email found yet." },
  webmail: { label: "Webmail address", sentence: "The only address is a webmail one (gmail, orange.fr…) — never emailed." },
  "no-phone": { label: "No phone", sentence: "No phone number on file." },
  "gb-unknown": { label: "Company or sole trader? unknown", sentence: "UK: no email until the register confirms it is a company." },
  "gb-sole": { label: "UK sole trader", sentence: "UK sole trader: consent is required before any email." },
  chain: { label: "Chain", sentence: "Part of a brand." },
  wiped: { label: "Contact details wiped", sentence: "Personal contact fields were wiped after the notice period." },
  deadline: { label: "Notice due in {n} days", sentence: "No notice sent yet: contact before the date or the purge wipes the contact fields." },
  "deadline-passed": { label: "Notice overdue", sentence: "No notice within 30 days: the purge wipes the contact fields." },
  lead: { label: "In conversation", sentence: "The lead replied, or a meeting or proposal is under way." },
  "lead-open": { label: "Lead: {stage}", sentence: "A lead exists and is still open." },
  "lead-closed": { label: "Lead: {stage}", sentence: "The lead is closed." },
};

export const LEAD_STAGE_WORDS: Record<string, string> = {
  new: "new",
  contacted: "contacted",
  replied: "replied",
  meeting: "meeting",
  proposal: "proposal",
  won: "won",
  lost: "lost",
  no_response: "no response",
  stop: "stopped",
};

/** Refusal codes → sentences; the panels never show the code. */
export const REFUSAL_TEXT: Record<RefusalCode, string> = {
  country_blocked: "No email rule for this country — call or write by hand",
  no_email: "No business email on file",
  email_webmail: "The only address is a webmail one — never emailed",
  email_sole_trader_consent: "Sole trader: consent is required before an email",
  email_unknown_legal_form: "Legal form unknown — call instead",
  optout_listed: "On the opposition list — no more contact",
  emailed_recently: "Emailed in the last 90 days",
  max_emails_reached: "Daily email limit reached",
  audit_missing: "The website has not been audited yet",
  audit_stale: "The audit is older than 90 days — run it again",
  daily_cap: "Daily email limit reached",
  forbids_extraction: "The website forbids prospecting",
  register_inactive: "Closed in the register",
  register_partial: "Not listed publicly in the register",
  notice_deadline_passed: "The 30-day notice window has passed",
  not_a_fit: "Marked not a fit",
  draft_unreviewed: "The email draft has not been reviewed",
  stage_closed: "The lead is closed",
  lead_in_conversation: "Already in conversation",
  call_window_closed: "Outside calling hours (weekdays 10–13, 14–20 local)",
  call_attempts_exceeded: "Four call attempts already in the last 30 days",
  call_screening_missing: "UK number not screened against TPS yet",
};

/** French nature_juridique codes → words. */
export const LEGAL_FORM_TEXT: Record<string, string> = {
  "1000": "sole trader",
  "5710": "SAS",
  "5720": "SASU",
  "5499": "SARL",
  "5498": "EURL",
  "5599": "SA",
  "5505": "SA",
  "9220": "association",
  "6540": "SCI",
};

export function legalFormWords(code: string | null | undefined): string {
  if (!code) return "legal form unknown";
  const c = code.trim();
  return LEGAL_FORM_TEXT[c] ?? (/^\d{4}$/.test(c) ? `other legal form (${c})` : c);
}

export const PROSPECT_TEXT = {
  intro: "Ready to send: the audit is done, the score is low enough, and there is a business email we may write to. Everything else is waiting for an audit, a call, or your decision.",
  addByWebsite: "Add a business by its website",
  more: "More",
  auditNext: "Audit next 20",
  fillTowns: "Fill in missing towns",
  labelsTitle: "What the labels mean",
  notAudited: "Not audited yet",
  scoreTitle: "0–100, lower means more to fix; A good · B average · C weak",
  emailKind: {
    generic: "generic address (contact@)",
    named: "named person",
    sole_trader: "sole trader's address",
    webmail: "webmail",
    unknown: "unknown kind",
  } as Record<string, string>,
  fromSite: "(from the site)",
  fromSource: "(from the source)",
  identityTitle: "Identity & register",
  websiteTitle: "Website & contact",
  recheck: "Re-check the register",
  registerToast: "Register: {state}, {listing}",
  registerWiped: " — contact details wiped",
  registerFailed: "The register could not be reached — nothing changed. Try again later.",
  noticeNotSent: "Notice not sent — due {date} (in {days} days)",
  noticeOverdue: "Notice overdue — was due {date}",
  noticeSent: "Notice sent {date}",
  wiped: "Contact details wiped {date}",
  whatAuditFound: "What the audit found",
  emailOverride: "Email to use instead",
  phoneOverride: "Phone to use instead",
  language: "Language of the report and emails",
  fit: "Fit",
  fitUnknown: "Not decided",
  fitYes: "Good fit",
  fitNo: "Not a fit",
  fitReason: "Why not a fit",
  notThisBusiness: "Not this business",
  overrideReason: "Allow prospecting despite the site's terms — reason",
  foundBy: "Found by the search “{area} · {trade}” on {date}",
  open: "open",
  coordsFrom: {
    source: "Coordinates from {source}",
    centre: "Coordinates from the area centre (approximate)",
    manual: "Coordinates entered by hand",
  } as Record<string, string>,
  whyNotYet: "Why this cannot go out yet",
  smtpOff: "Email sending is not configured on this server",
  frRule: "France (B2B email rules)",
  gbRule: "United Kingdom (corporate email only)",
  usRule: "United States (CAN-SPAM)",
  noRule: "No email rule for {country}",
  sentToday: "{n} of {cap} emails sent today",
  callsIn30d: "{n} of {max} calls in the last 30 days",
  registerUnreachable: "The register could not be reached — nothing was sent. Try again later.",
} as const;

export const TODAY_TEXT = {
  calls: "Calls to make",
  emails: "Emails ready to send",
  followUps: "Follow-ups",
  reports: "Reports opened, no reply",
  notices: "Notices due within 5 days",
  findBusinesses: "Find businesses",
  nextCall: "Next call",
  week: "This week: {n} new leads ({by})",
  housekeeping: "Housekeeping",
  sentToday: "{n} of {cap} sent today",
} as const;

/** Tokens that must never reach the admin UI (§7); wording.test.ts walks every string above. */
export const FORBIDDEN_TOKENS: RegExp[] = [/\bOSM\b/i, /FR reg/i, /\bpartial\b/i, /http_/i, /GOOGLE_PLACES/i, /\btiles?\b/i, /Nominatim/i, /Overpass/i, /\bcaveat\b/i, /\bISO2\b/i, /\bCH\b/, /\b[a-z]+_[a-z_]+\b/];
